accent = "#FF007F"
cursor = "#FF007F"
foreground = "#E0E6F0"
background = "#09090E"
selection_foreground = "#09090E"
selection_background = "#FF007F"

color0 = "#151521"
color1 = "#FF007F"
color2 = "#00FF9F"
color3 = "#FFE700"
color4 = "#00E5FF"
color5 = "#BD00FF"
color6 = "#00FFFF"
color7 = "#E0E6F0"
color8 = "#44445A"
color9 = "#FF3399"
color10 = "#33FFB2"
color11 = "#FFF033"
color12 = "#33EAFF"
color13 = "#CA33FF"
color14 = "#33FFFF"
color15 = "#FFFFFF"
