background = #09090E
foreground = #E0E6F0
cursor-color = #FF007F
selection-background = #FF007F
selection-foreground = #09090E

palette = 0=#151521
palette = 1=#FF007F
palette = 2=#00FF9F
palette = 3=#FFE700
palette = 4=#00E5FF
palette = 5=#BD00FF
palette = 6=#00FFFF
palette = 7=#E0E6F0
palette = 8=#44445A
palette = 9=#FF3399
palette = 10=#33FFB2
palette = 11=#FFF033
palette = 12=#33EAFF
palette = 13=#CA33FF
palette = 14=#33FFFF
palette = 15=#FFFFFF
